
services:
  frontend:
    build: ./packages/frontend
    ports:
      - "5173:5173"
    env_file:
      - ./packages/frontend/.env
    depends_on:
      - backend
  
  backend:
    build: ./packages/backend
    ports:
      - "4000:4000"
    env_file:
      - ./packages/backend/.env
    
    environment:
      - DATABASE_URL=mysql://root:${DB_PASSWORD}@database:3306/${DB_NAME}
  
  database:
    image: mysql:9.1.0-oracle    
    ports:
      - "3307:3306"
    env_file:
      - ./packages/backend/.env
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD:-rootpassword}
      MYSQL_DATABASE: ${DB_NAME}
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data: